title: Resume
resume:
  name: 李 俊秋
  jobtitle: Java工程师
  contact:
    - icon: fa-envelope
      text: akikun829@162.com
    - icon: fa-phone-square
      text: +86-18351937779
    - icon: fa-globe
      text: https://aki.ink
      link: https://aki.ink
    - icon: fa-github
      text: ancient2now
      link: https://github.com/ancient2now
  education:
    - university: 南京工程学院
      duration: Sep 2013 - July 2017
      location: 江苏 - 南京
      major: 软件工程
  skills:
    - title: 编程语言以及框架
      items: Java, Python, Spring相关, Akka
    - title: 服务相关
      items: Redis, Kafka, Neo4j, Jenkins, MySql, Oracle, PostgreSql
  experience:
    - title: 研发工程师
      duration: May 2017 - Now
      company: 富士通南大软件技术有限公司
      description: 
  projects:
    - name: HW公有云开发
      duration: Sep 2018 - Now
      description: {
        1. 基于Java，进行OpenStack Neutron组件重构
        2. 独立开发接口模块，完成文档，优化组件，SQL设计
      }
      contribution: Contributor.
    - name: Luses(Linuex update support expert system)
      description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      contribution: Creator and maintainer.
  languages:
    - name: English
      proficiency: TOEIC 660
    - name: Mandarin Chinese
      proficiency: Native
